package Pojos;
// Generated Nov 1, 2018 12:37:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DataDarah generated by hbm2java
 */
public class DataDarah  implements java.io.Serializable {


     private int idDarah;
     private String golonganDarah;
     private String resus;
     private String pendonor;
     private Date tanggalDonor;
     private String alamatPendonor;

    public DataDarah() {
    }

    public DataDarah(int idDarah, String golonganDarah, String resus, String pendonor, Date tanggalDonor, String alamatPendonor) {
       this.idDarah = idDarah;
       this.golonganDarah = golonganDarah;
       this.resus = resus;
       this.pendonor = pendonor;
       this.tanggalDonor = tanggalDonor;
       this.alamatPendonor = alamatPendonor;
    }
   
    public int getIdDarah() {
        return this.idDarah;
    }
    
    public void setIdDarah(int idDarah) {
        this.idDarah = idDarah;
    }
    public String getGolonganDarah() {
        return this.golonganDarah;
    }
    
    public void setGolonganDarah(String golonganDarah) {
        this.golonganDarah = golonganDarah;
    }
    public String getResus() {
        return this.resus;
    }
    
    public void setResus(String resus) {
        this.resus = resus;
    }
    public String getPendonor() {
        return this.pendonor;
    }
    
    public void setPendonor(String pendonor) {
        this.pendonor = pendonor;
    }
    public Date getTanggalDonor() {
        return this.tanggalDonor;
    }
    
    public void setTanggalDonor(Date tanggalDonor) {
        this.tanggalDonor = tanggalDonor;
    }
    public String getAlamatPendonor() {
        return this.alamatPendonor;
    }
    
    public void setAlamatPendonor(String alamatPendonor) {
        this.alamatPendonor = alamatPendonor;
    }




}


