package pojos;
// Generated Nov 28, 2018 7:59:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pengiriman generated by hbm2java
 */
public class Pengiriman  implements java.io.Serializable {


     private int idPengiriman;
     private long idPesanan;
     private Date tanggalKirim;
     private String statusPengiriman;

    public Pengiriman() {
    }

    public Pengiriman(int idPengiriman, long idPesanan, Date tanggalKirim, String statusPengiriman) {
       this.idPengiriman = idPengiriman;
       this.idPesanan = idPesanan;
       this.tanggalKirim = tanggalKirim;
       this.statusPengiriman = statusPengiriman;
    }
   
    public int getIdPengiriman() {
        return this.idPengiriman;
    }
    
    public void setIdPengiriman(int idPengiriman) {
        this.idPengiriman = idPengiriman;
    }
    public long getIdPesanan() {
        return this.idPesanan;
    }
    
    public void setIdPesanan(long idPesanan) {
        this.idPesanan = idPesanan;
    }
    public Date getTanggalKirim() {
        return this.tanggalKirim;
    }
    
    public void setTanggalKirim(Date tanggalKirim) {
        this.tanggalKirim = tanggalKirim;
    }
    public String getStatusPengiriman() {
        return this.statusPengiriman;
    }
    
    public void setStatusPengiriman(String statusPengiriman) {
        this.statusPengiriman = statusPengiriman;
    }




}


