package pojos;
// Generated Dec 17, 2018 1:43:05 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pesanan generated by hbm2java
 */
public class Pesanan  implements java.io.Serializable {


     private Integer idPesanan;
     private int idDarah;
     private String namaRs;
     private String alamatRs;
     private Date tanggalPesan;

    public Pesanan() {
    }

    public Pesanan(int idDarah, String namaRs, String alamatRs, Date tanggalPesan) {
       this.idDarah = idDarah;
       this.namaRs = namaRs;
       this.alamatRs = alamatRs;
       this.tanggalPesan = tanggalPesan;
    }
   
    public Integer getIdPesanan() {
        return this.idPesanan;
    }
    
    public void setIdPesanan(Integer idPesanan) {
        this.idPesanan = idPesanan;
    }
    public int getIdDarah() {
        return this.idDarah;
    }
    
    public void setIdDarah(int idDarah) {
        this.idDarah = idDarah;
    }
    public String getNamaRs() {
        return this.namaRs;
    }
    
    public void setNamaRs(String namaRs) {
        this.namaRs = namaRs;
    }
    public String getAlamatRs() {
        return this.alamatRs;
    }
    
    public void setAlamatRs(String alamatRs) {
        this.alamatRs = alamatRs;
    }
    public Date getTanggalPesan() {
        return this.tanggalPesan;
    }
    
    public void setTanggalPesan(Date tanggalPesan) {
        this.tanggalPesan = tanggalPesan;
    }




}


