package pojos;
// Generated Nov 28, 2018 7:59:37 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pesanan generated by hbm2java
 */
public class Pesanan  implements java.io.Serializable {


     private long idPesanan;
     private int idDarah;
     private String namaRs;
     private String alamatRs;
     private Date tanggalPesan;
     private String statusPesanan;

    public Pesanan() {
    }

	
    public Pesanan(long idPesanan, int idDarah, String namaRs, String alamatRs, Date tanggalPesan) {
        this.idPesanan = idPesanan;
        this.idDarah = idDarah;
        this.namaRs = namaRs;
        this.alamatRs = alamatRs;
        this.tanggalPesan = tanggalPesan;
    }
    public Pesanan(long idPesanan, int idDarah, String namaRs, String alamatRs, Date tanggalPesan, String statusPesanan) {
       this.idPesanan = idPesanan;
       this.idDarah = idDarah;
       this.namaRs = namaRs;
       this.alamatRs = alamatRs;
       this.tanggalPesan = tanggalPesan;
       this.statusPesanan = statusPesanan;
    }
   
    public long getIdPesanan() {
        return this.idPesanan;
    }
    
    public void setIdPesanan(long idPesanan) {
        this.idPesanan = idPesanan;
    }
    public int getIdDarah() {
        return this.idDarah;
    }
    
    public void setIdDarah(int idDarah) {
        this.idDarah = idDarah;
    }
    public String getNamaRs() {
        return this.namaRs;
    }
    
    public void setNamaRs(String namaRs) {
        this.namaRs = namaRs;
    }
    public String getAlamatRs() {
        return this.alamatRs;
    }
    
    public void setAlamatRs(String alamatRs) {
        this.alamatRs = alamatRs;
    }
    public Date getTanggalPesan() {
        return this.tanggalPesan;
    }
    
    public void setTanggalPesan(Date tanggalPesan) {
        this.tanggalPesan = tanggalPesan;
    }
    public String getStatusPesanan() {
        return this.statusPesanan;
    }
    
    public void setStatusPesanan(String statusPesanan) {
        this.statusPesanan = statusPesanan;
    }




}


