package Pojos;
// Generated Nov 1, 2018 12:37:59 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pesanan generated by hbm2java
 */
public class Pesanan  implements java.io.Serializable {


     private int idPesanan;
     private Date tanggalPesan;
     private Date tanggalKirim;

    public Pesanan() {
    }

    public Pesanan(int idPesanan, Date tanggalPesan, Date tanggalKirim) {
       this.idPesanan = idPesanan;
       this.tanggalPesan = tanggalPesan;
       this.tanggalKirim = tanggalKirim;
    }
   
    public int getIdPesanan() {
        return this.idPesanan;
    }
    
    public void setIdPesanan(int idPesanan) {
        this.idPesanan = idPesanan;
    }
    public Date getTanggalPesan() {
        return this.tanggalPesan;
    }
    
    public void setTanggalPesan(Date tanggalPesan) {
        this.tanggalPesan = tanggalPesan;
    }
    public Date getTanggalKirim() {
        return this.tanggalKirim;
    }
    
    public void setTanggalKirim(Date tanggalKirim) {
        this.tanggalKirim = tanggalKirim;
    }




}


