package pojos;
// Generated Dec 3, 2018 8:05:09 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable,Comparable<User> {


     private String password;
     private String username;

    public User() {
    }

    public User(String password, String username) {
       this.password = password;
       this.username = username;
    }
   
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    public String toJson() {
        return "{\"email\":\"" + getUsername()+ "\",\"password\":\"" + getPassword()+ "\"}";
    }
    
    @Override
    public int compareTo(User user) {
        return this.username.compareTo(user.username);
    }


}


